# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"prepare_and_launch": "00_launch.ipynb"}

modules = ["launch.py"]

doc_url = "https://lukexyz.github.io/orbital/"

git_url = "https://github.com/lukexyz/orbital/tree/master/"

def custom_doc_links(name): return None
