# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_launch.ipynb (unless otherwise specified).

__all__ = ['prepare_and_launch']

# Cell
import pandas as pd
import altair as alt
from pathlib import Path
import streamlit as st
from rocketpy import Environment, SolidMotor, Rocket, Flight

# Cell
def prepare_and_launch(datapath=''):

    # Creating an Environment for Starbase, Boca Chica
    Env = Environment(
        railLength=5.2,
        latitude=25.996845,
        longitude=-97.155086,
        elevation=0
    )
    # Create Motor
    Pro75M1670 = SolidMotor(
        thrustSource=f"{datapath}Cesaroni_M1670.eng",
        burnOut=3.9,
        grainNumber=5,
        grainSeparation=5/1000,
        grainDensity=1815,
        grainOuterRadius=33/1000,
        grainInitialInnerRadius=15/1000,
        grainInitialHeight=120/1000,
        nozzleRadius=33/1000,
        throatRadius=11/1000,
        interpolationMethod='linear'
    )


    # Creating a Rocket
    Calisto = Rocket(
        motor=Pro75M1670,
        radius=127/2000,
        mass=19.197-2.956,
        inertiaI=6.60,
        inertiaZ=0.0351,
        distanceRocketNozzle=-1.255,
        distanceRocketPropellant=-0.85704,
        powerOffDrag=f"{datapath}powerOffDragCurve.csv",
        powerOnDrag=f"{datapath}powerOnDragCurve.csv")

    Calisto.setRailButtons([0.2, -0.5])

    NoseCone = Calisto.addNose(length=0.55829, kind="vonKarman", distanceToCM=0.71971)

    FinSet = Calisto.addFins(4, span=0.100, rootChord=0.120, tipChord=0.040, distanceToCM=-1.04956)

    Tail = Calisto.addTail(topRadius=0.0635, bottomRadius=0.0435, length=0.060, distanceToCM=-1.194656)

    # Simulate flight
    TestFlight = Flight(rocket=Calisto, environment=Env, inclination=85, heading=0)
    TestFlight.plotAttitudeData()
    return TestFlight

